on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # <--- Ensure this matches your project's requirement 

      # Tell setup-uv where your project files are
      - name: Install uv in src/python
        uses: astral-sh/setup-uv@v1
        with:
          working-directory: src/python  # <--- Use this input
          enable-cache: true
          cache-dependency-glob: 'src/python/uv.lock' 
          
      # Since setup-uv created the venv in src/python, 
      # subsequent commands need to run from the same directory.
      - name: Sync dependencies
        run: uv sync --locked
        working-directory: src/python  # <--- Use the standard working-directory key
        
      - name: Run tests
        run: uv run main.py
        working-directory: src/python
